"""add second major and minor to user

Revision ID: 13a05cf2f84c
Revises: e452bbd88fdd
Create Date: 2026-05-13 11:07:31.199302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13a05cf2f84c'
down_revision = 'e452bbd88fdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_creator_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_status_start_at'))

    with op.batch_alter_table('event_attendee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_attendee_user_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_attendee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_attendee_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_status_start_at'), ['status', 'start_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_creator_user_id'), ['creator_user_id'], unique=False)

    # ### end Alembic commands ###
