"""Add second major and minor

Revision ID: 7f52aa609685
Revises: 13a05cf2f84c
Create Date: 2026-05-13 11:35:29.874177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f52aa609685'
down_revision = '13a05cf2f84c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('second_major', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('minor', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('minor')
        batch_op.drop_column('second_major')

    # ### end Alembic commands ###
